// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNakdfSbXfBgw-xYKUp6uFJTp2W_JhrLk',
    appId: '1:492544469047:web:ebd35e2845badc1f7777b2',
    messagingSenderId: '492544469047',
    projectId: 'job-board-and-freelance',
    authDomain: 'job-board-and-freelance.firebaseapp.com',
    storageBucket: 'job-board-and-freelance.firebasestorage.app',
    measurementId: 'G-XVB630DDCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUqrRvb-V1Wc5iQgQWyXorGSJkSOXnxjk',
    appId: '1:492544469047:android:5d83769edd07631b7777b2',
    messagingSenderId: '492544469047',
    projectId: 'job-board-and-freelance',
    storageBucket: 'job-board-and-freelance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9J1oFeI-AmwKo9uDku4we6ZY9AL4dswE',
    appId: '1:492544469047:ios:9915076b45957f9c7777b2',
    messagingSenderId: '492544469047',
    projectId: 'job-board-and-freelance',
    storageBucket: 'job-board-and-freelance.firebasestorage.app',
    iosBundleId: 'com.example.jobBoardFreelanceMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9J1oFeI-AmwKo9uDku4we6ZY9AL4dswE',
    appId: '1:492544469047:ios:9915076b45957f9c7777b2',
    messagingSenderId: '492544469047',
    projectId: 'job-board-and-freelance',
    storageBucket: 'job-board-and-freelance.firebasestorage.app',
    iosBundleId: 'com.example.jobBoardFreelanceMarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNakdfSbXfBgw-xYKUp6uFJTp2W_JhrLk',
    appId: '1:492544469047:web:5148fe7348bfffbe7777b2',
    messagingSenderId: '492544469047',
    projectId: 'job-board-and-freelance',
    authDomain: 'job-board-and-freelance.firebaseapp.com',
    storageBucket: 'job-board-and-freelance.firebasestorage.app',
    measurementId: 'G-23EQXEDMHC',
  );
}
